// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5W-whJXzbXH2fTMR3co5W3MkCF8uCcKk',
    appId: '1:102557304661:web:718835e6d920072e4b51dc',
    messagingSenderId: '102557304661',
    projectId: 'chatapp-db6f0',
    authDomain: 'chatapp-db6f0.firebaseapp.com',
    storageBucket: 'chatapp-db6f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjtL2tKF2JtQRDafTuzKSKXE2qoZIiLlg',
    appId: '1:102557304661:android:2da2b980cebf5af04b51dc',
    messagingSenderId: '102557304661',
    projectId: 'chatapp-db6f0',
    storageBucket: 'chatapp-db6f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8XHpJHAFHJwQgjy0o35kxJ444Zfx2hb4',
    appId: '1:102557304661:ios:38a5d4a194ea7f244b51dc',
    messagingSenderId: '102557304661',
    projectId: 'chatapp-db6f0',
    storageBucket: 'chatapp-db6f0.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8XHpJHAFHJwQgjy0o35kxJ444Zfx2hb4',
    appId: '1:102557304661:ios:38a5d4a194ea7f244b51dc',
    messagingSenderId: '102557304661',
    projectId: 'chatapp-db6f0',
    storageBucket: 'chatapp-db6f0.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5W-whJXzbXH2fTMR3co5W3MkCF8uCcKk',
    appId: '1:102557304661:web:13cf91fe3d4370cc4b51dc',
    messagingSenderId: '102557304661',
    projectId: 'chatapp-db6f0',
    authDomain: 'chatapp-db6f0.firebaseapp.com',
    storageBucket: 'chatapp-db6f0.appspot.com',
  );
}
